<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12"/>
        <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.12"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="Moq" Version="4.20.72"/>
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Microsoft.AspNetCore.Mvc.Testing">
            <HintPath>..\..\..\..\..\..\..\..\.nuget\packages\microsoft.aspnetcore.mvc.testing\10.0.12\lib\net10.0\Microsoft.AspNetCore.Mvc.Testing.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.AspNetCore.TestHost">
            <HintPath>..\..\..\..\..\..\..\..\.nuget\packages\microsoft.aspnetcore.testhost\10.0.12\lib\net10.0\Microsoft.AspNetCore.TestHost.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\MRX.Core\test\MRX.Core.TestHost\MRX.Core.TestHost.csproj"/>
        <ProjectReference Include="..\..\src\MRX.UI.ErrorsAutoWiring.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

</Project>