<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>true</IsPackable>
        <Version>1.0.0-rc1</Version>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Description>Lightweight JSON Path tokenizing and walking library for traversing and matching nodes within JSON documents.</Description>
        <PackageTags>mrx;json;jsonpath</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath=""/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="MRX.Json.Tests"/>
        <InternalsVisibleTo Include="MRX.Json.Reflection"/>
        <InternalsVisibleTo Include="MRX.Json.Reflection.Tests"/>

        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
        <InternalsVisibleTo Include="MRX.Core"/>
        <InternalsVisibleTo Include="MRX.UI.ErrorsAutoWiring"/>
        <InternalsVisibleTo Include="MRX.UI.ErrorsAutoWiring.Tests"/>
        <InternalsVisibleTo Include="MRX.UI.ErrorsAutoWiring.Blazor.Tests"/>
    </ItemGroup>

</Project>
