<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="MRX.Json.Tests"/>
        <InternalsVisibleTo Include="MRX.Json.Reflection"/>
        <InternalsVisibleTo Include="MRX.Json.Reflection.Tests"/>

        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
        <InternalsVisibleTo Include="MRX.Core"/>
        <InternalsVisibleTo Include="MRX.UI.ErrorsAutoWiring"/>
        <InternalsVisibleTo Include="MRX.UI.ErrorsAutoWiring.Tests"/>
        <InternalsVisibleTo Include="MRX.UI.ErrorsAutoWiring.Blazor.Tests"/>
    </ItemGroup>

</Project>
