<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>true</IsPackable>
        <Version>1.0.0-rc2</Version>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Description>Generic parsing abstractions for converting string input into typed values.</Description>
        <PackageTags>mrx;parsing</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath=""/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="MRX.Parsing.Tests"/>
        <InternalsVisibleTo Include="MRX.Parsing.Reflection"/>
    </ItemGroup>

</Project>
