<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\MRX.Core.Common\src\MRX.Core.Common.csproj" />
        <ProjectReference Include="..\..\MRX.Json\src\MRX.Json\MRX.Json.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="MRX.Core.Tests"/>
    </ItemGroup>

</Project>
